name: Lint Code Base
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_PHP: true
          VALIDATE_MARKDOWN: true
          VALIDATE_CSS: true
          VALIDATE_HTML: true
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}